name: Smart Contract Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Run Forge Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Run Forge tests
        run: forge test -vvv
